{% set version = "2.1.1" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-reprex
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/reprex_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/reprex/reprex_{{ version }}.tar.gz
  sha256: c860368cbc7ef90ea786fb61ab6fa42cd89b5258be48652abc20ad414001879c

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-callr >=3.6.0
    - r-cli >=3.2.0
    - r-clipr >=0.4.0
    - r-fs
    - r-glue
    - r-knitr >=1.23
    - r-lifecycle
    - r-rlang >=1.0.0
    - r-rmarkdown
    - r-rstudioapi
    - r-withr >=2.3.0
    - pandoc >=2.0
  run:
    - r-base
    - r-callr >=3.6.0
    - r-cli >=3.2.0
    - r-clipr >=0.4.0
    - r-fs
    - r-glue
    - r-knitr >=1.23
    - r-lifecycle
    - r-rlang >=1.0.0
    - r-rmarkdown
    - r-rstudioapi
    - r-withr >=2.3.0
    - pandoc >=2.0

test:
  commands:
    - $R -e "library('reprex')"           # [not win]
    - "\"%R%\" -e \"library('reprex')\""  # [win]

about:
  home: https://reprex.tidyverse.org, https://github.com/tidyverse/reprex#readme
  license: MIT
  summary: "Convenience wrapper that uses the 'rmarkdown' package to render small snippets of code to target formats that include both code and output. The goal is to encourage the sharing of small, reproducible, and runnable examples on code-oriented websites, such as <https://stackoverflow.com> and <https://github.com>,
    or in email. The user's clipboard is the default source of input code and the default target for rendered output. 'reprex' also extracts clean, runnable R code from various common formats, such as copy/paste from an R session. "
  license_family: MIT
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/MIT
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: reprex
# Title: Prepare Reproducible Example Code via the Clipboard
# Version: 0.3.0
# Authors@R: c( person("Jennifer", "Bryan", , "jenny@rstudio.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-6983-2759") ), person("Jim", "Hester", , "james.hester@rstudio.com", role = "aut", comment = c(ORCID = "0000-0002-2739-7082") ), person("David", "Robinson", , "admiral.david@gmail.com", role = "aut"), person("Hadley", "Wickham", , "hadley@rstudio.com", role = "aut", comment = c(ORCID = "0000-0003-4757-117X") ), person("RStudio", role = c("cph", "fnd")) )
# Description: Convenience wrapper that uses the 'rmarkdown' package to render small snippets of code to target formats that include both code and output. The goal is to encourage the sharing of small, reproducible, and runnable examples on code-oriented websites, such as <https://stackoverflow.com> and <https://github.com>, or in email. The user's clipboard is the default source of input code and the default target for rendered output. 'reprex' also extracts clean, runnable R code from various common formats, such as copy/paste from an R session.
# License: MIT + file LICENSE
# URL: https://reprex.tidyverse.org, https://github.com/tidyverse/reprex#readme
# BugReports: https://github.com/tidyverse/reprex/issues
# Depends: R (>= 3.1)
# Imports: callr (>= 2.0.0), clipr (>= 0.4.0), fs, rlang, rmarkdown, utils, whisker, withr
# Suggests: covr, devtools, fortunes, knitr, miniUI, rprojroot, rstudioapi, shiny, styler (>= 1.0.2), testthat (>= 2.0.0)
# VignetteBuilder: knitr
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.1.1
# SystemRequirements: pandoc (>= 1.12.3) - http://pandoc.org
# NeedsCompilation: no
# Packaged: 2019-05-16 13:41:23 UTC; jenny
# Author: Jennifer Bryan [aut, cre] (<https://orcid.org/0000-0002-6983-2759>), Jim Hester [aut] (<https://orcid.org/0000-0002-2739-7082>), David Robinson [aut], Hadley Wickham [aut] (<https://orcid.org/0000-0003-4757-117X>), RStudio [cph, fnd]
# Maintainer: Jennifer Bryan <jenny@rstudio.com>
# Repository: CRAN
# Date/Publication: 2019-05-16 16:20:05 UTC
