appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: OZv45AhpKeXWGcPg0D2tUDVqbrmSVkU+QGp/eUkytD7fAZ8a781wg4zOLrdu56Enevm2MVnczHkRpoLcLM7EXA8SBVkYB+IsgW7LJ3YDaS/t+gCsIOnyMuyfWbGNpgXZVmlDRuVeye9n81vqyDFWEXrBa30/2olETWtHRHQ45D2hKdYfQA6H5p+sJD4WjjNHDfoqXzb5j+XYNJ2sWg7aGzNKj6y+TGUFJEdIHvYLlLL508pGhlhyWDmKk1sD4+vYq6m/QMOdKX6vjunAlY3zH+B8yofXIUONsAQfNgG7YH2e0aBxqfvBVkNKov4urvcjEXNhpymXndKyQcOZlPIhaxmNp33psOG5IX/QB/d1AwaifbJedjjtCDYUm3L67HbXDGtrHmcrWIw1qOxaAyyWbLNcCdp0LdwHeWR7Yy8po5Dbob3wD2eZBrcA+Itiuc683C8ggDtkGiHk8qTDuTIQzkfnvAYTjhEAwTx3jxAebAXnYgiEESTahWdki//M4dHU1SOotneDUrQmbbQnniFlabZ0rSA9rjaYFt2u8Y0egpYZF3SNDsuAjjws+6ggf5KiXOyGtz0S8Irqu5fDbNl8tE482Q822pA0uNVaft3vZ4wcj64gTi7HpGVHuouFTr0wD3+BLLYANOlf7CrE1pZiVnOB8dcJ547LlQzNkQzvbVg=}
